# Generated by Django 2.2.3 on 2019-07-28 01:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_id', models.CharField(max_length=100)),
                ('character_id', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Placed', 'Placed'), ('Processing', 'Processing'), ('Rejected', 'Rejected'), ('Complete', 'Complete')], default='Placed', max_length=10)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
